"""Closed phrase contract for the playback-time keyword spotter.

Sherpa-ONNX exposes both the configured result label and the decoded token
sequence.  The shipped keyword file intentionally collapses several phrases to
``stop`` or ``wait`` labels, so the label alone is not enough to decide whether
the assistant just spoke the same phrase.  This module binds each exact token
row back to its canonical surface phrase without loading or executing a model.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
import os
from pathlib import Path
from typing import Optional


_MAX_KEYWORDS_FILE_BYTES = 64 * 1024
_MAX_TOKENS_PER_PHRASE = 64


@dataclass(frozen=True, slots=True)
class KwsStopPhrase:
    """One shipped STOP-only phrase and its collapsed Sherpa result label."""

    words: tuple[str, ...]
    tokens: tuple[str, ...]
    word_token_counts: tuple[int, ...]
    result_label: str
    threshold: float

    @property
    def surface(self) -> str:
        return " ".join(self.words).lower()


KWS_STOP_PHRASES: tuple[KwsStopPhrase, ...] = (
    KwsStopPhrase(("STOP",), ("S", "T", "AA1", "P"), (4,), "stop", 0.25),
    KwsStopPhrase(
        ("STOP", "TALKING"),
        ("S", "T", "AA1", "P", "T", "AO1", "K", "IH0", "NG"),
        (4, 5),
        "stop",
        0.25,
    ),
    KwsStopPhrase(
        ("STOP", "SPEAKING"),
        ("S", "T", "AA1", "P", "S", "P", "IY1", "K", "IH0", "NG"),
        (4, 6),
        "stop",
        0.25,
    ),
    KwsStopPhrase(
        ("BE", "QUIET"),
        ("B", "IY1", "K", "W", "AY1", "AH0", "T"),
        (2, 5),
        "stop",
        0.25,
    ),
    KwsStopPhrase(("WAIT",), ("W", "EY1", "T"), (3,), "wait", 0.30),
    KwsStopPhrase(
        ("HOLD", "ON"),
        ("HH", "OW1", "L", "D", "AA1", "N"),
        (4, 2),
        "wait",
        0.30,
    ),
)


@dataclass(frozen=True, slots=True)
class KwsPhraseBinding:
    """Exact decoded-token identity for one configured surface phrase."""

    tokens: tuple[str, ...]
    word_token_counts: tuple[int, ...]
    surface: str
    result_label: str


def _finite_marker(part: str, prefix: str, *, unit_interval: bool) -> bool:
    if type(part) is not str or not part.startswith(prefix) or len(part) == 1:
        return False
    try:
        value = float(part[1:])
    except (TypeError, ValueError, OverflowError):
        return False
    if not math.isfinite(value):
        return False
    return 0.0 <= value <= 1.0 if unit_interval else value > 0.0


def load_kws_phrase_bindings(path: str) -> tuple[KwsPhraseBinding, ...]:
    """Load the ordered six-row keyword contract generated by setup.

    Threshold values may be tuned, but row order, token identity, and collapsed
    labels stay closed. Runtime own-echo ambiguity still checks every surface in
    a collapsed label group: row order is local setup provenance, not a claim
    that phone tokens independently authenticate natural-language words.
    """

    if type(path) is not str or not path:
        raise ValueError("KWS keywords file path must be a non-empty string")
    source = Path(path)
    with source.open("rb") as handle:
        before = os.fstat(handle.fileno())
        if before.st_size <= 0 or before.st_size > _MAX_KEYWORDS_FILE_BYTES:
            raise ValueError("KWS keywords file exceeds its bounded contract")
        raw = handle.read(_MAX_KEYWORDS_FILE_BYTES + 1)
        after = os.fstat(handle.fileno())
    before_identity = (
        before.st_dev,
        before.st_ino,
        before.st_size,
        before.st_mtime_ns,
    )
    after_identity = (
        after.st_dev,
        after.st_ino,
        after.st_size,
        after.st_mtime_ns,
    )
    if (
        before_identity != after_identity
        or len(raw) != before.st_size
        or len(raw) > _MAX_KEYWORDS_FILE_BYTES
    ):
        raise ValueError("KWS keywords file changed while it was read")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError("KWS keywords file must be UTF-8") from exc
    lines = text.splitlines()
    if len(lines) != len(KWS_STOP_PHRASES) or any(not line.strip() for line in lines):
        raise ValueError("KWS keywords file must contain the exact shipped rows")

    bindings: list[KwsPhraseBinding] = []
    seen_tokens: set[tuple[str, ...]] = set()
    for line, expected in zip(lines, KWS_STOP_PHRASES, strict=True):
        parts = line.split()
        marker_at = next(
            (index for index, part in enumerate(parts) if part[:1] in (":", "#", "@")),
            -1,
        )
        if marker_at <= 0 or len(parts) - marker_at != 3:
            raise ValueError("KWS keyword row has an invalid token/marker shape")
        token_parts = parts[:marker_at]
        markers = parts[marker_at:]
        if (
            len(token_parts) > _MAX_TOKENS_PER_PHRASE
            or any(type(token) is not str or not token for token in token_parts)
            or not _finite_marker(markers[0], ":", unit_interval=False)
            or not _finite_marker(markers[1], "#", unit_interval=True)
            or markers[2] != f"@{expected.result_label}"
        ):
            raise ValueError("KWS keyword row does not match the shipped contract")
        tokens = tuple(token_parts)
        if tokens != expected.tokens:
            raise ValueError("KWS keyword row does not match the pinned phone tokens")
        if tokens in seen_tokens:
            raise ValueError("KWS keyword token rows must be unique")
        seen_tokens.add(tokens)
        bindings.append(
            KwsPhraseBinding(
                tokens=tokens,
                word_token_counts=expected.word_token_counts,
                surface=expected.surface,
                result_label=expected.result_label,
            )
        )
    return tuple(bindings)


def resolve_kws_stop_binding(
    bindings: tuple[KwsPhraseBinding, ...],
    *,
    result_label: str,
    tokens: object,
) -> Optional[KwsPhraseBinding]:
    """Resolve one exact native result to its closed STOP-only binding."""

    if (
        type(bindings) is not tuple
        or len(bindings) != len(KWS_STOP_PHRASES)
        or type(result_label) is not str
        or type(tokens) not in (list, tuple)
    ):
        return None
    if not 0 < len(tokens) <= _MAX_TOKENS_PER_PHRASE:
        return None
    if any(type(token) is not str or not token for token in tokens):
        return None
    token_tuple = tuple(tokens)
    matches: list[KwsPhraseBinding] = []
    seen_binding_tokens: set[tuple[str, ...]] = set()
    for binding, expected in zip(bindings, KWS_STOP_PHRASES, strict=True):
        if (
            type(binding) is not KwsPhraseBinding
            or type(binding.tokens) is not tuple
            or not 0 < len(binding.tokens) <= _MAX_TOKENS_PER_PHRASE
            or any(type(token) is not str or not token for token in binding.tokens)
            or binding.tokens != expected.tokens
            or type(binding.word_token_counts) is not tuple
            or binding.word_token_counts != expected.word_token_counts
            or len(binding.word_token_counts) != len(expected.words)
            or any(
                type(count) is not int or count <= 0
                for count in binding.word_token_counts
            )
            or sum(binding.word_token_counts) != len(binding.tokens)
            or type(binding.surface) is not str
            or binding.surface != expected.surface
            or type(binding.result_label) is not str
            or binding.result_label != expected.result_label
            or binding.tokens in seen_binding_tokens
        ):
            return None
        seen_binding_tokens.add(binding.tokens)
        if binding.tokens == token_tuple and binding.result_label == result_label:
            matches.append(binding)
    if len(matches) != 1:
        return None
    return matches[0]


def resolve_kws_stop_phrase(
    bindings: tuple[KwsPhraseBinding, ...],
    *,
    result_label: str,
    tokens: object,
) -> Optional[str]:
    """Compatibility wrapper returning the canonical phrase surface."""

    binding = resolve_kws_stop_binding(
        bindings,
        result_label=result_label,
        tokens=tokens,
    )
    return None if binding is None else binding.surface


def collapsed_label_surfaces(result_label: str) -> tuple[str, ...]:
    """Return all shipped phrases behind a collapsed label, for safe fallback."""

    if type(result_label) is not str:
        return ()
    return tuple(
        phrase.surface
        for phrase in KWS_STOP_PHRASES
        if phrase.result_label == result_label
    )
